apiVersion: v1
kind: PersistentVolume
metadata:
  name: templates-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""          # conflicto con 'standard'
  hostPath:                     # apunta al directorio montado en Minikube
    path: /data/templates
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: templates-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""          # evita provisión dinámica
  volumeName: templates-pv      # usar este PV específico
